---
name: Docs
on:
  push:
    branches:
      - main
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          name: pfhub
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
      - run: echo "UID=${UID}" >> $GITHUB_ENV
      - uses: actions/cache/restore@v3
        with:
          path: /run/user/${{ env.UID }}/http_cache.sqlite
          key: ${{ runner.os}}-http_cache.sqlite
      - run: nix develop --command bash -c "mkdocs gh-deploy --clean --verbose --remote-branch nist-pages"
      - uses: actions/cache/save@v3
        if: always()
        with:
          path: /run/user/${{ env.UID }}/http_cache.sqlite
          key: ${{ runner.os }}-http_cache.sqlite
