# Nix flake checker determines the health of the flake.lock files.
# See https://determinate.systems/posts/flake-checker for some
# explanation. This checks that the branches that are relied on for
# packages are maintained and have recent commits. If they aren't
# maintained then the checker will notify us and we can update the
# lock or flake files.
---
name: Test Flakes
on: [push, pull_request]
jobs:
  test-flakes:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Check Nix flake inputs (./flake.lock)
        uses: DeterminateSystems/flake-checker-action@v5
      - name: Build Nix package
        run: |
          nix build
